# Generated by Django 5.1.4 on 2025-01-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
